interface ICovidCasesStates {
  AC: {value: number};
  AL: {value: number};
  AP: {value: number};
  AM: {value: number};
  BA: {value: number};
  CE: {value: number};
  DF: {value: number};
  ES: {value: number};
  GO: {value: number};
  MA: {value: number};
  MT: {value: number};
  MS: {value: number};
  MG: {value: number};
  PA: {value: number};
  PB: {value: number};
  PR: {value: number};
  PE: {value: number};
  PI: {value: number};
  RJ: {value: number};
  RN: {value: number};
  RS: {value: number};
  RO: {value: number};
  RR: {value: number};
  SC: {value: number};
  SP: {value: number};
  SE: {value: number};
  TO: {value: number};
}

export default ICovidCasesStates;
